# Generated by Django 5.2.7 on 2025-10-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='channels/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='episodes/'),
        ),
    ]
