# Generated by Django 5.2.7 on 2025-10-21 05:26

import podcasts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_channel_thumbnail_episode_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='channels/', validators=[podcasts.validators.validate_image_file_extension, podcasts.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='episodes/', validators=[podcasts.validators.validate_audio_file_extension, podcasts.validators.validate_audio_file_size]),
        ),
    ]
