"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta  # ← JWT 토큰 수명 설정을 위해 필수 1
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0pg7ov91ayw08wzz*$gk!gpnqz9h5ij@a441i$2vb1z1n381lq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',  # ← 로그아웃 기능을 위해 필수 2
    'podcasts',
    'analysis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# REST Framework 설정 추가 (파일 맨 아래)
REST_FRAMEWORK = {
     # 기본 인증 방식 설정 3
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # JWT 인증을 기본으로 사용
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

WSGI_APPLICATION = 'config.wsgi.application'
SPECTACULAR_SETTINGS = {
    'TITLE': 'Podcasts API',
    'DESCRIPTION': 'API for podcasts',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}
# JWT 설정 4
SIMPLE_JWT = {
    # Access Token 수명
    # 짧게 설정하여 보안 강화 (탈취되어도 금방 만료)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    # 실무 권장: 15분~1시간
    # MVP 단계: 1시간 (개발 편의)

    # Refresh Token 수명
    # 길게 설정하여 사용자 편의 향상
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # 실무 권장: 7일~30일

    # Token 자동 갱신 여부
    # True: Refresh 시 Refresh Token도 새로 발급
    # False: Refresh Token은 그대로 유지
    'ROTATE_REFRESH_TOKENS': True,
    # 권장: True (보안 강화)

    # 이전 Refresh Token 무효화 여부
    # ROTATE_REFRESH_TOKENS=True일 때만 의미 있음
    'BLACKLIST_AFTER_ROTATION': True,
    # 권장: True (이전 토큰 재사용 방지)

    # 서명 알고리즘
    'ALGORITHM': 'HS256',
    # HS256: 대칭키 암호화 (서버만 복호화 가능)
    # RS256: 비대칭키 (공개키로 검증 가능) - MSA 환경에 유리

    # 서명 키 (Django SECRET_KEY 사용)
    'SIGNING_KEY': SECRET_KEY,
    # 프로덕션: 별도의 JWT_SECRET_KEY 사용 권장

    # Payload에 포함할 사용자 식별 필드
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Token 헤더 이름
    'AUTH_HEADER_TYPES': ('Bearer',),
    # 요청 시: Authorization: Bearer <token>

    # Token 헤더 이름
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 파일 처리를 위한 세팅
# settings.py 설정 추가 -> MEDIA_ROOT, MEDIA_URL 추가
# MEDIA_ROOT: 파일 저장 경로 -> media 폴더 생성
# url.py 설정 추가 -> static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 추가
# 2:20까지 진행하고 다음 내용으로 넘어가겠습니다!

# CORS 설정
