# Generated by Django 5.2.7 on 2025-10-21 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcasts', '0003_alter_channel_thumbnail_alter_episode_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_logs', to='podcasts.episode')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
